Traceback (most recent call last):
  File "C:\Python\Miniconda\envs\workspace_JB\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Python\Miniconda\envs\workspace_JB\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Python\Miniconda\envs\workspace_JB\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Python\Miniconda\envs\workspace_JB\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Python\Miniconda\envs\workspace_JB\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Python\Miniconda\envs\workspace_JB\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Python\Miniconda\envs\workspace_JB\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Python\Miniconda\envs\workspace_JB\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
flash1 = flash_isothermal_ssi(mr1, np.array([0.2, 0.8])).flash_isothermal_ssi_run(P, T, phases='og')
G = np.sum(np.array([G1, G2]) * flash1.F, axis=0)
L1 = np.sum(z * flash1.eos.lnf[0], axis=1)
L2 = np.sum(z * flash1.eos.lnf[1], axis=1)
L = np.sum(np.array([L1, L2]) * flash1.F, axis=0)
D = G - L
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_1704\1231123915.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [0mflash1[0m [1;33m=[0m [0mflash_isothermal_ssi[0m[1;33m([0m[0mmr1[0m[1;33m,[0m [0mnp[0m[1;33m.[0m[0marray[0m[1;33m([0m[1;33m[[0m[1;36m0.2[0m[1;33m,[0m [1;36m0.8[0m[1;33m][0m[1;33m)[0m[1;33m)[0m[1;33m.[0m[0mflash_isothermal_ssi_run[0m[1;33m([0m[0mP[0m[1;33m,[0m [0mT[0m[1;33m,[0m [0mphases[0m[1;33m=[0m[1;34m'og'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0mG[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0msum[0m[1;33m([0m[0mnp[0m[1;33m.[0m[0marray[0m[1;33m([0m[1;33m[[0m[0mG1[0m[1;33m,[0m [0mG2[0m[1;33m][0m[1;33m)[0m [1;33m*[0m [0mflash1[0m[1;33m.[0m[0mF[0m[1;33m,[0m [0maxis[0m[1;33m=[0m[1;36m0[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [0mL1[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0msum[0m[1;33m([0m[0mz[0m [1;33m*[0m [0mflash1[0m[1;33m.[0m[0meos[0m[1;33m.[0m[0mlnf[0m[1;33m[[0m[1;36m0[0m[1;33m][0m[1;33m,[0m [0maxis[0m[1;33m=[0m[1;36m1[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0mL2[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0msum[0m[1;33m([0m[0mz[0m [1;33m*[0m [0mflash1[0m[1;33m.[0m[0meos[0m[1;33m.[0m[0mlnf[0m[1;33m[[0m[1;36m1[0m[1;33m][0m[1;33m,[0m [0maxis[0m[1;33m=[0m[1;36m1[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [0mL[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0msum[0m[1;33m([0m[0mnp[0m[1;33m.[0m[0marray[0m[1;33m([0m[1;33m[[0m[0mL1[0m[1;33m,[0m [0mL2[0m[1;33m][0m[1;33m)[0m [1;33m*[0m [0mflash1[0m[1;33m.[0m[0mF[0m[1;33m,[0m [0maxis[0m[1;33m=[0m[1;36m0[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mAttributeError[0m: type object 'Object' has no attribute 'F'
AttributeError: type object 'Object' has no attribute 'F'

